### ISSUE TITLE
It works ... only partly :(

### ISSUE THREAD

**Issue by bergenm** [Kravalg/linkedin-bot#1]
Hi Krava, 

nice job you've done here ! 
Actually it has been a year or so now, and unfortunately the bot isn't working, because it is scrolling but not clicking on the button.. 

It would be awesome if you have time to help me in that?

**Comment by Kravalg** [comment]
Yes, of course I will try to help you

**Comment by Kravalg** [comment]
@bergenm Thank you for your message, if there are more questions - please, and I will gladly help

**Comment by Audelweiss** [comment]
Hello, I have the same problem : it scrolls but it doesn't click...
But nice job ;)

**Comment by Kravalg** [comment]
@Audelweiss 
Thank you for your question:) maybe you have too many contacts, and therefore many possible contacts. So the infinite scroll. Specifically for this I've entered the setting - countOfPagesScrolled, which is responsible for the number of pages that the script will scroll. The default is 5 pages. You can change the number 5 to any other.
