### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by NoThrowForwardIt** [Kravalg/linkedin-bot#2]
hey buddy, The bot does not work on the new version of linkedin

1: URL change

https://www.linkedin.com/people/pymk/hub  >>>   https://www.linkedin.com/mynetwork/

thanks for good work.

**Comment by Kravalg** [comment]
@ironbits Thanks for support. But I have still the old version of Linkedin. If you can please tell me where you are geographically, I could use a vpn to see the new version of the design.

Or maybe you know how to switch otherwise the old design to the new.

**Comment by NoThrowForwardIt** [comment]
@Kravalg thanks for support, im live on Brazil, but this new version is not avaliable to all users yet.

**Comment by Kravalg** [comment]
@ironbits 
here and I about the same :)
soon will release an update for the new version of the design.
thanks for the help
