### ISSUE TITLE
Fix Line #15

### ISSUE THREAD

**Issue by frutilla-ha** [Kravalg/linkedin-bot#6]
jQuery.each( $('.artdeco-button'), 	function() {
jQuery.each( $('.artdeco-button__text'), 	function() {
The replace class ".artdeco-button" to class " artdeco-button__text" after script work(https://www.linkedin.com/mynetwork/) this page. Your work help people. Thank you. 
https://github.com/Kravalg/linkedin-bot/blob/8423155a5ad05efce5a57ed162303e33c174b72f/linkedinBot.js#L15

**Comment by Kravalg** [comment]
Thank you, but this repository is no longer supported
